### ISSUE TITLE
Enable Travis access

### ISSUE THREAD

**Issue by unixorn** [dotfiles/dotfiles.github.com#128]
#127 adds a travis configuration file to check the links in index.md & README.md. @pengwynn, please enable access to the repo for travis.

**Comment by pengwynn** [comment]
@unixorn Great idea. Just approved it.

**Comment by unixorn** [comment]
Thanks @pengwynn. We should probably add a `build.md` that includes a link to the graphic of the latest build's status. That, or add a badge somewhere in `index.md`

**Comment by dkhamsing** [comment]
@pengwynn hi I was checking https://travis-ci.org/dotfiles and ur says no active repo setup

**Comment by unixorn** [comment]
@pengwynn I think you will have to activate this on the travis-ci.org site as a repo owner, I can't do it as a collaborator.

**Comment by pengwynn** [comment]
> We should probably add a build.md that includes a link to the graphic of the latest build's status. That, or add a badge somewhere in index.md

@unixorn If you find that useful go for it. I'm not sure we'd know about missing links unless a new build was run. We'd only have a new build on PRs, right? 

> I think you will have to activate this on the travis-ci.org site as a repo owner, I can't do it as a collaborator.

It took a while for Travis to sync my account. I finally got the toggle switch to activate it. I think we're all set now.

**Comment by dkhamsing** [comment]
@pengwynn You can have Travis check for each commit and pull request (default)
