### ISSUE TITLE
Add bare git repo method of dotfile management

### ISSUE THREAD

**Issue by andrew-kennedy** [dotfiles/dotfiles.github.com#135]
As referenced [here](https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/). Didn't see it on the page and though it would be good to add.

**Comment by JoeSchr** [comment]
I think that's a good idea. After scanning through almost every project on this page, I finally found this one and liked it the most, because you need no tools and no symlinks and can use branches for different OS with no bash support (eg. windows) but still can use `git` knowledge.

**Comment by unixorn** [comment]
Should have closed it when #250 was merged
