### ISSUE TITLE
Info on dotfile basics

### ISSUE THREAD

**Issue by matthewriley** [dotfiles/dotfiles.github.com#15]
Some folks might be newish to dotfiles. How about a section covering dotfile basics or links out to blog posts that do? Could be helpful. Thanks.

**Comment by unixorn** [comment]
I added an intro article in #77, do you have any other suggestions for articles I should link in?

**Comment by unixorn** [comment]
I'm going to close this. If you have any suggested links to add in addition to the ones I included in #77, please open a new issue.

Thanks!
