### ISSUE TITLE
overwhelming is an understatement

### ISSUE THREAD

**Issue by bedge** [dotfiles/dotfiles.github.com#186]
Yes, it's great, fantastic stuff, but the one thing I'm having issues with is digesting it all.
Not complaining, just suggesting.

Be great to see some stats on the main page for stuff like:
- activity/popularity/most-forked/cloned
- target audience, eg:
    - noob, new machine, do it all for me
    - existing config, what won't destroy what I have
- focus by packages
    - tmux/vim/zsh
- focus by package manager
    - vundle/vimplug/
    - oh-my-zsh/....

**Comment by neeasade** [comment]
https://rizonrice.github.io/resources

**Comment by anishathalye** [comment]
Can this issue be closed now, due to #257?

**Comment by unixorn** [comment]
Yes, closing
