### ISSUE TITLE
Please add chef_dotfile_manager_tutorial to the tutorial section

### ISSUE THREAD

**Issue by jbwyatt4** [dotfiles/dotfiles.github.com#206]
Hello GitHub,

chef_dotfile_manager_tutorial is a complete bootstrap for dotfiles that allows you to use Chef and Ruby to manage your dotfiles. This includes Chef's excellent package and template tools.

https://gitlab.com/jbwyatt4/chef_dotfile_manager_tutorial

**Comment by unixorn** [comment]
Please add details in [README.md](https://gitlab.com/jbwyatt4/chef_dotfile_manager_tutorial/blob/master/README.md) about what exactly is going to get installed, and what platforms it supports.

**Comment by jbwyatt4** [comment]
I added more details to the Readme including what is being installed and what platforms are supported.
