### ISSUE TITLE
Table of contents / anchors

### ISSUE THREAD

**Issue by sparr** [dotfiles/dotfiles.github.com#207]
The right side of the page has gotten very long, and the left side has some open space. It would be nice if the left side had a small table of contents linking to anchors for the headings on the right.

* Get started with a bootstrap
* Go further with a framework
  * General-purpose dotfile utilities (this deserves to be promoted)
* Tutorials
* Don’t ignore your .gitignore (should be sub-heading'd?)
* Embrace submodules / subtrees (should be sub-heading'd?)
* FAQ
* Contribute

**Comment by anishathalye** [comment]
I think this is fixed by #257; maybe this issue can be closed now?
