### ISSUE TITLE
Periodic update of star counts

### ISSUE THREAD

**Issue by anishathalye** [dotfiles/dotfiles.github.com#275]
Right now, star counts are updated manually by `script/update-star-count.py`. It would be nice if we could make this automatic, e.g. once a month.

It would be straightforward to write a bot to do this; where could we host such a bot?

(moved here from #274)

**Comment by anishathalye** [comment]
To reply to @unixorn's question from @274, it looks like it's possible to push to a repo using GitHub actions: https://github.com/ad-m/github-push-action

**Comment by TheLocehiliosan** [comment]
Probably possible to do via Travis-CI or something similar.

**Comment by unixorn** [comment]
I don't have time to work on it this week or next, unfortunately.

**Comment by 0-vortex** [comment]
Been playing around with actions lately, can pick this one up over the weekend :D
