### ISSUE TITLE
face dotfile, contact info, backgrounds, audio settings?

### ISSUE THREAD

**Issue by nebulousdog** [dotfiles/dotfiles.github.com#281]
Hi, I'm curious if there are best practices for the login `.face` dotfile, the [contact info](https://help.ubuntu.com/stable/ubuntu-help/contacts-edit-details.html.en) for your user info that is often available if a person finds your computer, saved background screenshots (or at least the setting to point your screenshots to a dir), and audio settings? Thanks. This was a useful repo to learn from.

**Comment by unixorn** [comment]
This is the first I'm hearing about `.face` files. They may be a ubuntu-specific thing, I don't know of any best practices for them.
