### ISSUE TITLE
Set default apps for MacOS

### ISSUE THREAD

**Issue by Pavelas** [dotfiles/dotfiles.github.com#299]
Good day,

This is not an issue, but maybe it will be useful for someone else as well. I am looking for commands to do the following changes:

- Change default Mac OS Mail client to another application.
- Change default "Open with:" application for specific extensions, for example: .md, .txt and others.

I would appreciate any help!

**Comment by unixorn** [comment]
That's kind of out of scope for this repo - it collects setups, it's not really meant for OS-specific questions.

That said, have a look at https://github.com/bkuhlmann/mac_os-config, it does a lot of app install and macOS configuration.
