### ISSUE TITLE
> @pengwynn - I'd like to switch from travis to either circleCI or GitHub actions, but I need to be an owner to enable that.

### ISSUE THREAD

**Issue by katukatr** [dotfiles/dotfiles.github.com#348]
> @pengwynn - I'd like to switch from travis to either circleCI or GitHub actions, but I need to be an owner to enable that.

_Originally posted by @katukatr in https://github.com/dotfiles/dotfiles.github.com/issues/252#issuecomment-1404447831_

**Comment by katukatr** [comment]
> ```
>           > @pengwynn - I'd like to switch from travis to either circleCI or GitHub actions, but I need to be an owner to enable that.
> ```
> 
> 
>      
>   
> 
> _Originally posted by @katukatr in [#252 (comment)](https://github.com/dotfiles/dotfiles.github.com/issues/252#issuecomment-1404447831)_

**Comment by unixorn** [comment]
What is this supposed to mean? Issues should be actionable.
