### ISSUE TITLE
Which category would Dorothy belong under?

### ISSUE THREAD

**Issue by balupton** [dotfiles/dotfiles.github.com#363]
[Dorothy](https://github.com/bevry/dorothy): 🧙🏻‍♀️ Bring your dotfile commands and configuration to any shell. Sensible defaults and hundreds of commands preloaded. Supports Bash, Zsh, Fish, Nu, Xonsh, Elvish, Dash, KornShell, macOS, Linux, Windows.

It has hundreds of commands that work across multiple shells and operating systems, so could qualify for Bootstrap and Inspiration. It also fits the dotfile management of the general-purpose utilities. And it also provides scripts to help you write your own commands, so fits tool-specific frameworks.

**Comment by unixorn** [comment]
I'd go with bootstrap since it includes commands.
