### ISSUE TITLE
Compile with GitHub pages

### ISSUE THREAD

**Issue by twe4ked** [dotfiles/dotfiles.github.com#62]
There has been a lot of work done on GitHub pages since this was originally set up. I could take a crack at making it work without the pre-compile stage.

**Comment by twe4ked** [comment]
I won't be able to do this for a while. I'm travelling and my laptop was stolen. If this issue is still open in a few months I may get to it then :)

**Comment by unixorn** [comment]
Thanks, @twe4ked
